# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/ for more options

version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - temp
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/lex/fb2epub
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: var-declaration
        severity: warning
      - name: package-comments
        severity: warning

formatters:
  enable:
    - gofmt
    - goimports

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    # Exclude known linter issues
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    # Exclude G601 (implicit memory aliasing) - common in range loops with pointers
    - linters:
        - gosec
      text: "Implicit memory aliasing in for loop"
    # Exclude G304 (file inclusion) - we validate file paths
    - linters:
        - gosec
      text: "Potential file inclusion via variable"
    # Exclude G301 (directory permissions) - 0755 is standard for temp dirs
    - linters:
        - gosec
      text: "Expect directory permissions to be 0750 or less"
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-use-default: false
